name: static
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Disable AppArmor
        if: runner.os == 'Linux'
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - name: Generate coverage and badge
        run: |
          make test
          mkdir -p ./ci/out/static
          cp ./ci/out/coverage.html ./ci/out/static/coverage.html
          percent=$(go tool cover -func ./ci/out/coverage.prof | tail -n1 | awk '{print $3}' | tr -d '%')
          curl -L -o ./ci/out/static/coverage.svg "https://img.shields.io/badge/coverage-${percent}%25-success"
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./ci/out/static/
      - uses: actions/deploy-pages@v4
        id: deployment
